name: fixedwidth
description: A library for working with fixed width files in dart. Easily turn data to and convert from properly formatted fixed width strings with readable layout definitions.
version: 0.6.3
homepage: https://github.com/madisona/dart-fixedwidth

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: '>=5.12.0 <14.1.0'
  build: '>=2.0.0 <4.1.0'
  intl: '>=0.18.0 <0.21.0'
  source_gen: '>=1.5.0 <5.0.0'

dev_dependencies:
  build_runner: ^2.4.8
  lints: '>=2.0.0 <7.0.0'
  test: '>=1.24.4 <2.0.0'
