name: Dart CI Acceptance

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [3.0, stable, beta, dev]
    steps:
      - uses: actions/checkout@v7
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Generate Code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Check Formatting
        if: matrix.sdk == 'stable'
        run: dart format . --output=none --set-exit-if-changed

      - name: Analyze Code
        if: matrix.sdk == 'stable'
        run: dart analyze

      - name: Run Tests
        run: dart test