name: Dart CI Acceptance

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [3.8.0, stable, beta, dev]
    steps:
      - uses: actions/checkout@v7
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - run: dart pub get
      - run: dart format . --output=none --set-exit-if-changed
      - run: dart analyze
      - run: dart test